// source: lib/proto/test.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

goog.exportSymbol('proto.grpc.experiments.TestRequest', null, global);
goog.exportSymbol('proto.grpc.experiments.TestResponse', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.grpc.experiments.TestRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.grpc.experiments.TestRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.grpc.experiments.TestRequest.displayName = 'proto.grpc.experiments.TestRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.grpc.experiments.TestResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.grpc.experiments.TestResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.grpc.experiments.TestResponse.displayName = 'proto.grpc.experiments.TestResponse';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.grpc.experiments.TestRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.grpc.experiments.TestRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.grpc.experiments.TestRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.grpc.experiments.TestRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    field1: jspb.Message.getFieldWithDefault(msg, 1, ""),
    field2: jspb.Message.getFieldWithDefault(msg, 2, ""),
    field3: jspb.Message.getFieldWithDefault(msg, 3, ""),
    field4: jspb.Message.getFieldWithDefault(msg, 4, 0),
    field5: jspb.Message.getFieldWithDefault(msg, 5, 0),
    field6: jspb.Message.getFloatingPointFieldWithDefault(msg, 6, 0.0),
    field7: jspb.Message.getFloatingPointFieldWithDefault(msg, 7, 0.0),
    field8: jspb.Message.getBooleanFieldWithDefault(msg, 8, false)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.grpc.experiments.TestRequest}
 */
proto.grpc.experiments.TestRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.grpc.experiments.TestRequest;
  return proto.grpc.experiments.TestRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.grpc.experiments.TestRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.grpc.experiments.TestRequest}
 */
proto.grpc.experiments.TestRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setField1(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setField2(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setField3(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setField4(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setField5(value);
      break;
    case 6:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setField6(value);
      break;
    case 7:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setField7(value);
      break;
    case 8:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setField8(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.grpc.experiments.TestRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.grpc.experiments.TestRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.grpc.experiments.TestRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.grpc.experiments.TestRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getField1();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getField2();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getField3();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getField4();
  if (f !== 0) {
    writer.writeInt32(
      4,
      f
    );
  }
  f = message.getField5();
  if (f !== 0) {
    writer.writeInt64(
      5,
      f
    );
  }
  f = message.getField6();
  if (f !== 0.0) {
    writer.writeFloat(
      6,
      f
    );
  }
  f = message.getField7();
  if (f !== 0.0) {
    writer.writeDouble(
      7,
      f
    );
  }
  f = message.getField8();
  if (f) {
    writer.writeBool(
      8,
      f
    );
  }
};


/**
 * optional string field1 = 1;
 * @return {string}
 */
proto.grpc.experiments.TestRequest.prototype.getField1 = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.grpc.experiments.TestRequest} returns this
 */
proto.grpc.experiments.TestRequest.prototype.setField1 = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string field2 = 2;
 * @return {string}
 */
proto.grpc.experiments.TestRequest.prototype.getField2 = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.grpc.experiments.TestRequest} returns this
 */
proto.grpc.experiments.TestRequest.prototype.setField2 = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string field3 = 3;
 * @return {string}
 */
proto.grpc.experiments.TestRequest.prototype.getField3 = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.grpc.experiments.TestRequest} returns this
 */
proto.grpc.experiments.TestRequest.prototype.setField3 = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional int32 field4 = 4;
 * @return {number}
 */
proto.grpc.experiments.TestRequest.prototype.getField4 = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/**
 * @param {number} value
 * @return {!proto.grpc.experiments.TestRequest} returns this
 */
proto.grpc.experiments.TestRequest.prototype.setField4 = function(value) {
  return jspb.Message.setProto3IntField(this, 4, value);
};


/**
 * optional int64 field5 = 5;
 * @return {number}
 */
proto.grpc.experiments.TestRequest.prototype.getField5 = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/**
 * @param {number} value
 * @return {!proto.grpc.experiments.TestRequest} returns this
 */
proto.grpc.experiments.TestRequest.prototype.setField5 = function(value) {
  return jspb.Message.setProto3IntField(this, 5, value);
};


/**
 * optional float field6 = 6;
 * @return {number}
 */
proto.grpc.experiments.TestRequest.prototype.getField6 = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 6, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.grpc.experiments.TestRequest} returns this
 */
proto.grpc.experiments.TestRequest.prototype.setField6 = function(value) {
  return jspb.Message.setProto3FloatField(this, 6, value);
};


/**
 * optional double field7 = 7;
 * @return {number}
 */
proto.grpc.experiments.TestRequest.prototype.getField7 = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 7, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.grpc.experiments.TestRequest} returns this
 */
proto.grpc.experiments.TestRequest.prototype.setField7 = function(value) {
  return jspb.Message.setProto3FloatField(this, 7, value);
};


/**
 * optional bool field8 = 8;
 * @return {boolean}
 */
proto.grpc.experiments.TestRequest.prototype.getField8 = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 8, false));
};


/**
 * @param {boolean} value
 * @return {!proto.grpc.experiments.TestRequest} returns this
 */
proto.grpc.experiments.TestRequest.prototype.setField8 = function(value) {
  return jspb.Message.setProto3BooleanField(this, 8, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.grpc.experiments.TestResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.grpc.experiments.TestResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.grpc.experiments.TestResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.grpc.experiments.TestResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    field1: jspb.Message.getFieldWithDefault(msg, 1, ""),
    field2: jspb.Message.getFieldWithDefault(msg, 2, ""),
    field3: jspb.Message.getFieldWithDefault(msg, 3, ""),
    field4: jspb.Message.getFieldWithDefault(msg, 4, 0),
    field5: jspb.Message.getFieldWithDefault(msg, 5, 0),
    field6: jspb.Message.getFloatingPointFieldWithDefault(msg, 6, 0.0),
    field7: jspb.Message.getFloatingPointFieldWithDefault(msg, 7, 0.0),
    field8: jspb.Message.getBooleanFieldWithDefault(msg, 8, false)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.grpc.experiments.TestResponse}
 */
proto.grpc.experiments.TestResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.grpc.experiments.TestResponse;
  return proto.grpc.experiments.TestResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.grpc.experiments.TestResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.grpc.experiments.TestResponse}
 */
proto.grpc.experiments.TestResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setField1(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setField2(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setField3(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setField4(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setField5(value);
      break;
    case 6:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setField6(value);
      break;
    case 7:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setField7(value);
      break;
    case 8:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setField8(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.grpc.experiments.TestResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.grpc.experiments.TestResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.grpc.experiments.TestResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.grpc.experiments.TestResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getField1();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getField2();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getField3();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getField4();
  if (f !== 0) {
    writer.writeInt32(
      4,
      f
    );
  }
  f = message.getField5();
  if (f !== 0) {
    writer.writeInt64(
      5,
      f
    );
  }
  f = message.getField6();
  if (f !== 0.0) {
    writer.writeFloat(
      6,
      f
    );
  }
  f = message.getField7();
  if (f !== 0.0) {
    writer.writeDouble(
      7,
      f
    );
  }
  f = message.getField8();
  if (f) {
    writer.writeBool(
      8,
      f
    );
  }
};


/**
 * optional string field1 = 1;
 * @return {string}
 */
proto.grpc.experiments.TestResponse.prototype.getField1 = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.grpc.experiments.TestResponse} returns this
 */
proto.grpc.experiments.TestResponse.prototype.setField1 = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string field2 = 2;
 * @return {string}
 */
proto.grpc.experiments.TestResponse.prototype.getField2 = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.grpc.experiments.TestResponse} returns this
 */
proto.grpc.experiments.TestResponse.prototype.setField2 = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string field3 = 3;
 * @return {string}
 */
proto.grpc.experiments.TestResponse.prototype.getField3 = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.grpc.experiments.TestResponse} returns this
 */
proto.grpc.experiments.TestResponse.prototype.setField3 = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional int32 field4 = 4;
 * @return {number}
 */
proto.grpc.experiments.TestResponse.prototype.getField4 = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/**
 * @param {number} value
 * @return {!proto.grpc.experiments.TestResponse} returns this
 */
proto.grpc.experiments.TestResponse.prototype.setField4 = function(value) {
  return jspb.Message.setProto3IntField(this, 4, value);
};


/**
 * optional int64 field5 = 5;
 * @return {number}
 */
proto.grpc.experiments.TestResponse.prototype.getField5 = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/**
 * @param {number} value
 * @return {!proto.grpc.experiments.TestResponse} returns this
 */
proto.grpc.experiments.TestResponse.prototype.setField5 = function(value) {
  return jspb.Message.setProto3IntField(this, 5, value);
};


/**
 * optional float field6 = 6;
 * @return {number}
 */
proto.grpc.experiments.TestResponse.prototype.getField6 = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 6, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.grpc.experiments.TestResponse} returns this
 */
proto.grpc.experiments.TestResponse.prototype.setField6 = function(value) {
  return jspb.Message.setProto3FloatField(this, 6, value);
};


/**
 * optional double field7 = 7;
 * @return {number}
 */
proto.grpc.experiments.TestResponse.prototype.getField7 = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 7, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.grpc.experiments.TestResponse} returns this
 */
proto.grpc.experiments.TestResponse.prototype.setField7 = function(value) {
  return jspb.Message.setProto3FloatField(this, 7, value);
};


/**
 * optional bool field8 = 8;
 * @return {boolean}
 */
proto.grpc.experiments.TestResponse.prototype.getField8 = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 8, false));
};


/**
 * @param {boolean} value
 * @return {!proto.grpc.experiments.TestResponse} returns this
 */
proto.grpc.experiments.TestResponse.prototype.setField8 = function(value) {
  return jspb.Message.setProto3BooleanField(this, 8, value);
};


goog.object.extend(exports, proto.grpc.experiments);
